export const accessLogs = [
  {
    timestamp: "2078-03-18 11:23:17",
    user: "Orthol",
    location: "Docking Bay",
    result: "Denied",
    reason: "Invalid credentials",
  },
  {
    timestamp: "2078-03-17 19:25:42",
    user: "Astar",
    location: "Docking Bay",
    result: "Granted",
    reason: "Valid crew member",
  },
  {
    timestamp: "2078-03-17 14:57:03",
    user: "Zephyr",
    location: "Bridge",
    result: "Denied",
    reason: "Insufficient clearance",
  },
  {
    timestamp: "2078-03-17 13:01:15",
    user: "Nova",
    location: "Docking Bay",
    result: "Granted",
    reason: "Valid crew member",
  },
  {
    timestamp: "2078-03-16 18:34:44",
    user: "Vega",
    location: "Docking Bay",
    result: "Granted",
    reason: "Engineering clearance",
  },
  {
    timestamp: "2078-03-16 11:32:18",
    user: "Orion",
    location: "Bridge",
    result: "Denied",
    reason: "Insufficient clearance",
  },
  {
    timestamp: "2078-03-15 14:35:27",
    user: "Lyra",
    location: "Docking Bay",
    result: "Granted",
    reason: "Valid crew member",
  },
  {
    timestamp: "2078-03-15 04:37:52",
    user: "**************",
    location: "Bridge",
    result: "Granted",
    reason: "Sufficient clearance. Name redacted for security.",
  },
  {
    timestamp: "2078-03-14 22:04:13",
    user: "Stellar",
    location: "Bridge",
    result: "Denied",
    reason: "Insufficient clearance",
  },
  {
    timestamp: "2078-03-14 20:58:36",
    user: "Nebula",
    location: "Docking Bay",
    result: "Granted",
    reason: "Valid crew member",
  },
];
